version: "3"


services:
  container1:
    build: /root/pods/dockerfile1
  container2:
    build: /root/pods/dockerfile2
    ports:
      - "8070:80"
  container3:
    image: mysql:8.0.17 
    environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: testapp
    ports:
      - "3308:3306" 
  admin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
