version: "3"
services:
  container1:
    build: /root/assignment/dockerfile1
  container2:
    build: /root/assignment/dockerfile2
    ports:
      - "8070:80"
  container3:
    build: /root/assignment/dockerfile3
    ports:
      - "3308:3306" 
  test_db:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
